### ISSUE TITLE
Suggest - .so 能熱抽換的嗎

### ISSUE THREAD

**Issue by kevinlincg** [rocket049/pluginloader#1]
這個專案真的是太棒了
不知道能不能加個 .so的hot reload

**Comment by rocket049** [comment]
这个是基于官方的 `plugin` 库的简单包装，官方的 `plugin` 模块还没有主动 `unload` 功能。

你可以测试一下：变量失效后 `GC` 是否会释放已载入的 `plugin`.

**Comment by rocket049** [comment]
把新的 .so 的名字加上版本号，可以载入，但是旧的是否释放无法控制。
